export const REFRESH_CLICKED = 'REFRESH_CLICKED';
export const FETCH_ALL_STATE_SUCCESS = 'FETCH_ALL_STATE_SUCCESS';
export const FETCH_ALL_STATE_ERROR = 'FETCH_ALL_STATE_ERROR';
export const APP_MOUNTED = 'APP_MOUNTED';
export const PATCH_BOT_STATE_SUCCESS = 'PATCH_BOT_STATE_SUCCESS'
export const PATCH_BOT_STATE_ERROR = 'PATCH_BOT_STATE_ERROR';
export const BOT_PROPERTY_UPDATED = 'BOT_PROPERTY_UPDATED';
export const ENTER_KEY = 13;