export const REFRESH_CLICKED = 'REFRESH_CLICKED';
export const FETCH_ALL_STATE_SUCCESS = 'FETCH_ALL_STATE_SUCCESS';
export const FETCH_ALL_STATE_ERROR = 'FETCH_ALL_STATE_ERROR';
export const APP_MOUNTED = 'APP_MOUNTED';